### ISSUE TITLE
No auto-repeat in virtual keyboard and wrong Amiga screen size

### ISSUE THREAD

**Issue by Vweber73** [vAmigaWeb/vAmigaWeb.github.io#1]
Hi,

Very nice web-based C64 and Amiga emulators, congrats ! They work quite well on my Samsung Z 3 fold (Android).

One major issue is that on both emulators, the virtual keyboard does not allow key auto repeat when pressed long. This is a show stopper, for instance for flight simulators, like Fighter Pilot on C64 and F/A 18 Interceptor on Amiga... 

Also, none of the proposed screen sizes for the Amiga is satisfying (the C64 is fine): narrow has good proportions but cut the top line and some space on left and right. The others are too compressed vertically...

Finally, the joystick also does not seem to auto repeat the up direction (useful for firing in Gravity Force).

Any plan to add status bar for disk activity, and disk noise sound ? Support for ECS Denise, 68030 emulation, AGA would also be nice (but low priority, the keyboard is way more important !).

Many thanks and cheers,

Vincent

**Comment by mithrendal** [comment]
wrong repo ... this is the gh-pages repo of vAmigaWeb (where the builds are published) ... issue will be answered at the sourcecode repo see https://github.com/vAmigaWeb/vAmigaWeb/issues/68
